services:

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    networks:
      - opensearch-net

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3305:3306"
    networks:
      - opensearch-net

  mysql-primary:
    container_name: mysql-primary
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data_primary:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - opensearch-net

  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql-data-primary:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: root
  #   networks:
  #     - opensearch-net

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=my-cluster
      - node.name=my-node
      - discovery.type=single-node
      - "discovery.seed_hosts=opensearch"
      - "opensearch-node.attr.box_type=hot"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dopensearch.xcontent.depth.max=1000"
      # - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Djdk.tls.client.protocols=TLSv1.2 -Djavax.net.ssl.keyStore=/usr/share/opensearch/config/keystore.jks -Djavax.net.ssl.keyStorePassword=keystore_password -Djavax.net.ssl.trustStore=/usr/share/opensearch/config/truststore.jks -Djavax.net.ssl.trustStorePassword=truststore_password -Dcom.sun.net.ssl.checkRevocation=false -Djdk.tls.server.protocols=TLSv1.2 -Djavax.net.ssl.sessionCacheSize=20480
      # - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Djdk.tls.client.protocols=TLSv1.2 -Dcom.sun.net.ssl.checkRevocation=false -Djdk.tls.server.protocols=TLSv1.2 -Djavax.net.ssl.sessionCacheSize=20480
      - network.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - http.port=9200
      - transport.port=9300
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=myPass2403
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/certs/localhost.crt
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/certs/localhost.key
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/localhost.crt
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.transport.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/certs/localhost.crt
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/certs/localhost.key
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/localhost.crt
    ports:
      - "9200:9200"
      - "9600:9600" # For node communication
      - "9300:9300"
    volumes:
      # - ./opensearch-config:/usr/share/opensearch/config
      - ./opensearch-config/certs:/usr/share/opensearch/config/certs
      # - opensearch-data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
    - opensearch-net

  logstash:
    image: my-logstash-with-opensearch
    container_name: logstash
    volumes:
      - ./logstash-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash-config:/usr/share/logstash/config/certs
    environment:
      - "xpack.monitoring.enabled=false"
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  kafka_b:
    image: bitnami/kafka:3.4
    hostname: kafka_b
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      # - KAFKA_KRAFT_CLUSTER_ID=228f04bc-0895-11ee-be56-0242ac120002
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka_b:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      # - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2

  zookeeper:
    image: zookeeper:latest
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  flink-jobmanager:
    image: flink:1.18-java17
    container_name: jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml

  flink-taskmanager:
    image: flink:1.18-java17
    container_name: taskmanager
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink-jobmanager
    command: taskmanager
    links:
      - flink-jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

volumes:
  kafka_data:
    driver: local
  opensearch-data:
  db_data:

networks:
  opensearch-net:

