flink:
  jobmanager:
    rpc:
      address: localhost
      port: 6123
  taskmanager:
    slots: 4

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

## Logging properties
logging:
  file.name: /mnt/new_data/logs/Flink-Kafka-consumer.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com:
      example:
        flinkconsumer: DEBUG
    org.hibernate: ERROR