flink:
  jobmanager:
    rpc:
      address: localhost
      port: 6123
  taskmanager:
    slots: 4

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true